{
 "cells": [
  {
   "cell_type": "code",
   "execution_count":None,
   "id": "55e69a3a-2231-45ec-a09c-801fcbc1f307",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import torch\n",
    "from transformers import AutoModelForCausalLM, AutoTokenizer\n",
    "\n",
    "# Load model (use small for better performance)\n",
    "model_name = \"microsoft/DialoGPT-small\"\n",
    "tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
    "model = AutoModelForCausalLM.from_pretrained(model_name)\n",
    "\n",
    "# Page config\n",
    "st.set_page_config(page_title=\"AI Chatbot\", page_icon=\"🤖\")\n",
    "\n",
    "st.title(\"🤖 AI Chatbot\")\n",
    "st.write(\"Ask me anything!\")\n",
    "\n",
    "# Session state for chat history\n",
    "if \"chat_history_ids\" not in st.session_state:\n",
    "    st.session_state.chat_history_ids = None\n",
    "\n",
    "if \"messages\" not in st.session_state:\n",
    "    st.session_state.messages = []\n",
    "\n",
    "# Display previous messages\n",
    "for msg in st.session_state.messages:\n",
    "    with st.chat_message(msg[\"role\"]):\n",
    "        st.markdown(msg[\"content\"])\n",
    "\n",
    "# User input\n",
    "user_input = st.chat_input(\"Type your message...\")\n",
    "\n",
    "if user_input:\n",
    "    # Show user message\n",
    "    st.chat_message(\"user\").markdown(user_input)\n",
    "    st.session_state.messages.append({\"role\": \"user\", \"content\": user_input})\n",
    "\n",
    "    # Encode input\n",
    "    new_input_ids = tokenizer.encode(user_input + tokenizer.eos_token, return_tensors='pt')\n",
    "\n",
    "    # Add to history\n",
    "    bot_input_ids = torch.cat(\n",
    "        [st.session_state.chat_history_ids, new_input_ids],\n",
    "        dim=-1\n",
    "    ) if st.session_state.chat_history_ids is not None else new_input_ids\n",
    "\n",
    "    # Generate response\n",
    "    st.session_state.chat_history_ids = model.generate(\n",
    "        bot_input_ids,\n",
    "        max_length=500,\n",
    "        pad_token_id=tokenizer.eos_token_id,\n",
    "        do_sample=True,\n",
    "        top_k=50,\n",
    "        top_p=0.95,\n",
    "        temperature=0.75\n",
    "    )\n",
    "\n",
    "    # Decode response\n",
    "    response = tokenizer.decode(\n",
    "        st.session_state.chat_history_ids[:, bot_input_ids.shape[-1]:][0],\n",
    "        skip_special_tokens=True\n",
    "    )\n",
    "\n",
    "    # Show bot response\n",
    "    st.chat_message(\"assistant\").markdown(response)\n",
    "    st.session_state.messages.append({\"role\": \"assistant\", \"content\": response})"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
